export enum TaskType {
  RESEARCH = 'RESEARCH',
  WRITING = 'WRITING',
  EDITING = 'EDITING',
  TRANSLATION = 'TRANSLATION',
  DESIGN = 'DESIGN',
  DEVELOPMENT = 'DEVELOPMENT',
  ANALYSIS = 'ANALYSIS',
  CONSULTATION = 'CONSULTATION',
  OTHER = 'OTHER',
} 