export enum TaskType {
  ONLINE_TEST = 'Online Test',
  QUIZ = 'Quiz',
  MIDTERM_EXAM = 'Midterm Exam',
  FINAL_EXAM = 'Final Exam',
  ASSIGNMENT = 'Assignment',
  INDIVIDUAL_ASSIGNMENT = 'Individual Assignment',
  GROUP_ASSIGNMENT = 'Group Assignment',
  PROJECT = 'Project',
  SLIDES = 'Slides',
  ASSESSMENT = 'Assessment',
  FINAL_ASSIGNMENT = 'Final Assignment',
  TUTORIAL = 'Tutorial',
  PRACTICE = 'Practice',
  HOMEWORK = 'Homework',
  TEST = 'Test',
  PRESENTATION = 'Presentation',
  SCRIPT = 'Script',
  TUTORIAL_ASSIGNMENT = 'Tutorial Assignment',
  SUMMARY = 'Summary',
  DRAWING = 'Drawing',
  CODING = 'Coding',
  DESIGN = 'Design',
  EXAM = 'Exam',
  OTHER = 'Other',
} 