version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: jobsync-postgres
    environment:
      POSTGRES_DB: jobsync
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - jobsync-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: jobsync-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - jobsync-network

  # NestJS Application
  api:
    build: .
    container_name: jobsync-api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - DB_NAME=jobsync
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - postgres
      - redis
    networks:
      - jobsync-network
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  postgres_data:
  redis_data:

networks:
  jobsync-network:
    driver: bridge 