export enum Country {
  UNITED_STATES = 'United States',
  PAKISTAN = 'Pakistan',
  INDIA = 'India',
  AUSTRALIA = 'Australia',
  CANADA = 'Canada',
  UNITED_KINGDOM = 'United Kingdom',
  POLAND = 'Poland',
  KUWAIT = 'Kuwait',
  SAUDI_ARABIA = 'Saudi Arabia',
  UNITED_ARAB_EMIRATES = 'United Arab Emirates',
  KENYA = 'Kenya',
  QATAR = 'Qatar',
}

export enum Currency {
  USD = 'USD',
  PKR = 'PKR',
  INR = 'INR',
  AUD = 'AUD',
  CAD = 'CAD',
  GBP = 'GBP',
  EUR = 'EUR',
  KWD = 'KWD',
  AED = 'AED',
}

export enum TaskType {
  ONLINE_TEST = 'Online Test',
  QUIZ = 'Quiz',
  MIDTERM_EXAM = 'Midterm Exam',
  FINAL_EXAM = 'Final Exam',
  ASSIGNMENT = 'Assignment',
  INDIVIDUAL_ASSIGNMENT = 'Individual Assignment',
  GROUP_ASSIGNMENT = 'Group Assignment',
  PROJECT = 'Project',
  SLIDES = 'Slides',
  ASSESSMENT = 'Assessment',
  FINAL_ASSIGNMENT = 'Final Assignment',
  TUTORIAL = 'Tutorial',
  PRACTICE = 'Practice',
  HOMEWORK = 'Homework',
  TEST = 'Test',
  PRESENTATION = 'Presentation',
  SCRIPT = 'Script',
  TUTORIAL_ASSIGNMENT = 'Tutorial Assignment',
  SUMMARY = 'Summary',
  DRAWING = 'Drawing',
  CODING = 'Coding',
  DESIGN = 'Design',
  EXAM = 'Exam',
  OTHER = 'Other',
} 